data <- read.csv("household_power_consumption.txt",sep=";",colClasses = "character")
subData <- subset(data,(data$Date=="1/2/2007")|(data$Date=="2/2/2007"))
activePower <- as.numeric(subData$Global_active_power)
png(filename="plot1.png",width = 480,height = 480)
hist(activePower,col = "red",main = "Global Active Power",xlab = "Global Active Power (kilowatts)")
dev.off()