data <- read.csv("household_power_consumption.txt",sep=";",colClasses = "character")
subData <- subset(data,(data$Date=="1/2/2007")|(data$Date=="2/2/2007"))
dateTime <- strptime(paste0(subData$Date,subData$Time),"%d/%m/%Y%H:%M:%S")
sub1 <- as.numeric(subData$Sub_metering_1)
sub2 <- as.numeric(subData$Sub_metering_2)
sub3 <- as.numeric(subData$Sub_metering_3)
png(filename="plot3.png",width = 480,height = 480)
plot(dateTime,sub1,type = "l",xlab = "",ylab = "Energy sub metering")
lines(dateTime,sub2,col="red")
lines(dateTime,sub3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty="solid",col=c("black","red","blue"))
dev.off()